smps2asm2bin.exe "music/Mus81 - GHZ.asm" "cmp_music/Mus81 - GHZ.bin"
smps2asm2bin.exe "music/Mus82 - LZ.asm" "cmp_music/Mus82 - LZ.bin"
smps2asm2bin.exe "music/Mus83 - MZ.asm" "cmp_music/Mus83 - MZ.bin"
smps2asm2bin.exe "music/Mus84 - SLZ.asm" "cmp_music/Mus84 - SLZ.bin"
smps2asm2bin.exe "music/Mus85 - SYZ.asm" "cmp_music/Mus85 - SYZ.bin"
smps2asm2bin.exe "music/Mus86 - SBZ.asm" "cmp_music/Mus86 - SBZ.bin"
smps2asm2bin.exe "music/Mus87 - Invincibility.asm" "cmp_music/Mus87 - Invincibility.bin"
smps2asm2bin.exe "music/Mus88 - Extra Life.asm" "cmp_music/Mus88 - Extra Life.bin"
smps2asm2bin.exe "music/Mus89 - Special Stage.asm" "cmp_music/Mus89 - Special Stage.bin"
smps2asm2bin.exe "music/Mus8A - Title Screen.asm" "cmp_music/Mus8A - Title Screen.bin"
smps2asm2bin.exe "music/Mus8B - Ending.asm" "cmp_music/Mus8B - Ending.bin"
smps2asm2bin.exe "music/Mus8C - Boss.asm" "cmp_music/Mus8C - Boss.bin"
smps2asm2bin.exe "music/Mus8D - FZ.asm" "cmp_music/Mus8D - FZ.bin"
smps2asm2bin.exe "music/Mus8E - Sonic Got Through.asm" "cmp_music/Mus8E - Sonic Got Through.bin"
smps2asm2bin.exe "music/Mus8F - Game Over.asm" "cmp_music/Mus8F - Game Over.bin"
smps2asm2bin.exe "music/Mus90 - Continue Screen.asm" "cmp_music/Mus90 - Continue Screen.bin"
smps2asm2bin.exe "music/Mus91 - Credits.asm" "cmp_music/Mus91 - Credits.bin"
smps2asm2bin.exe "music/Mus92 - Drowning.asm" "cmp_music/Mus92 - Drowning.bin"
smps2asm2bin.exe "music/Mus93 - Get Emerald.asm" "cmp_music/Mus93 - Get Emerald.bin"
smps2asm2bin.exe "sfx/SndA0 - Jump.asm" "cmp_sfx/SndA0 - Jump.bin"
smps2asm2bin.exe "sfx/SndA1 - Lamppost.asm" "cmp_sfx/SndA1 - Lamppost.bin"
smps2asm2bin.exe "sfx/SndA2.asm" "cmp_sfx/SndA2.bin"
smps2asm2bin.exe "sfx/SndA3 - Death.asm" "cmp_sfx/SndA3 - Death.bin"
smps2asm2bin.exe "sfx/SndA4 - Skid.asm" "cmp_sfx/SndA4 - Skid.bin"
smps2asm2bin.exe "sfx/SndA5.asm" "cmp_sfx/SndA5.bin"
smps2asm2bin.exe "sfx/SndA6 - Hit Spikes.asm" "cmp_sfx/SndA6 - Hit Spikes.bin"
smps2asm2bin.exe "sfx/SndA7 - Push Block.asm" "cmp_sfx/SndA7 - Push Block.bin"
smps2asm2bin.exe "sfx/SndA8 - SS Goal.asm" "cmp_sfx/SndA8 - SS Goal.bin"
smps2asm2bin.exe "sfx/SndA9 - SS Item.asm" "cmp_sfx/SndA9 - SS Item.bin"
smps2asm2bin.exe "sfx/SndAA - Splash.asm" "cmp_sfx/SndAA - Splash.bin"
smps2asm2bin.exe "sfx/SndAB.asm" "cmp_sfx/SndAB.bin"
smps2asm2bin.exe "sfx/SndAC - Hit Boss.asm" "cmp_sfx/SndAC - Hit Boss.bin"
smps2asm2bin.exe "sfx/SndAD - Get Bubble.asm" "cmp_sfx/SndAD - Get Bubble.bin"
smps2asm2bin.exe "sfx/SndAE - Fireball.asm" "cmp_sfx/SndAE - Fireball.bin"
smps2asm2bin.exe "sfx/SndAF - Shield.asm" "cmp_sfx/SndAF - Shield.bin"
smps2asm2bin.exe "sfx/SndB0 - Saw.asm" "cmp_sfx/SndB0 - Saw.bin"
smps2asm2bin.exe "sfx/SndB1 - Electric.asm" "cmp_sfx/SndB1 - Electric.bin"
smps2asm2bin.exe "sfx/SndB2 - Drown Death.asm" "cmp_sfx/SndB2 - Drown Death.bin"
smps2asm2bin.exe "sfx/SndB3 - Flamethrower.asm" "cmp_sfx/SndB3 - Flamethrower.bin"
smps2asm2bin.exe "sfx/SndB4 - Bumper.asm" "cmp_sfx/SndB4 - Bumper.bin"
smps2asm2bin.exe "sfx/SndB5 - Ring.asm" "cmp_sfx/SndB5 - Ring.bin"
smps2asm2bin.exe "sfx/SndB6 - Spikes Move.asm" "cmp_sfx/SndB6 - Spikes Move.bin"
smps2asm2bin.exe "sfx/SndB7 - Rumbling.asm" "cmp_sfx/SndB7 - Rumbling.bin"
smps2asm2bin.exe "sfx/SndB8.asm" "cmp_sfx/SndB8.bin"
smps2asm2bin.exe "sfx/SndB9 - Collapse.asm" "cmp_sfx/SndB9 - Collapse.bin"
smps2asm2bin.exe "sfx/SndBA - SS Glass.asm" "cmp_sfx/SndBA - SS Glass.bin"
smps2asm2bin.exe "sfx/SndBB - Door.asm" "cmp_sfx/SndBB - Door.bin"
smps2asm2bin.exe "sfx/SndBC - Teleport.asm" "cmp_sfx/SndBC - Teleport.bin"
smps2asm2bin.exe "sfx/SndBD - ChainStomp.asm" "cmp_sfx/SndBD - ChainStomp.bin"
smps2asm2bin.exe "sfx/SndBE - Roll.asm" "cmp_sfx/SndBE - Roll.bin"
smps2asm2bin.exe "sfx/SndBF - Get Continue.asm" "cmp_sfx/SndBF - Get Continue.bin"
smps2asm2bin.exe "sfx/SndC0 - Basaran Flap.asm" "cmp_sfx/SndC0 - Basaran Flap.bin"
smps2asm2bin.exe "sfx/SndC1 - Break Item.asm" "cmp_sfx/SndC1 - Break Item.bin"
smps2asm2bin.exe "sfx/SndC2 - Drown Warning.asm" "cmp_sfx/SndC2 - Drown Warning.bin"
smps2asm2bin.exe "sfx/SndC3 - Giant Ring.asm" "cmp_sfx/SndC3 - Giant Ring.bin"
smps2asm2bin.exe "sfx/SndC4 - Bomb.asm" "cmp_sfx/SndC4 - Bomb.bin"
smps2asm2bin.exe "sfx/SndC5 - Cash Register.asm" "cmp_sfx/SndC5 - Cash Register.bin"
smps2asm2bin.exe "sfx/SndC6 - Ring Loss.asm" "cmp_sfx/SndC6 - Ring Loss.bin"
smps2asm2bin.exe "sfx/SndC7 - Chain Rising.asm" "cmp_sfx/SndC7 - Chain Rising.bin"
smps2asm2bin.exe "sfx/SndC8 - Burning.asm" "cmp_sfx/SndC8 - Burning.bin"
smps2asm2bin.exe "sfx/SndC9 - Hidden Bonus.asm" "cmp_sfx/SndC9 - Hidden Bonus.bin"
smps2asm2bin.exe "sfx/SndCA - Enter SS.asm" "cmp_sfx/SndCA - Enter SS.bin"
smps2asm2bin.exe "sfx/SndCB - Wall Smash.asm" "cmp_sfx/SndCB - Wall Smash.bin"
smps2asm2bin.exe "sfx/SndCC - Spring.asm" "cmp_sfx/SndCC - Spring.bin"
smps2asm2bin.exe "sfx/SndCD - Switch.asm" "cmp_sfx/SndCD - Switch.bin"
smps2asm2bin.exe "sfx/SndCE - Ring Left Speaker.asm" "cmp_sfx/SndCE - Ring Left Speaker.bin"
smps2asm2bin.exe "sfx/SndCF - Signpost.asm" "cmp_sfx/SndCF - Signpost.bin"
smps2asm2bin.exe "sfx/SndD0 - Waterfall.asm" "cmp_sfx/SndD0 - Waterfall.bin"
